# Generated by Django 3.0.8 on 2020-07-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200727_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='bk_service',
            field=models.BooleanField(default=False, help_text='Backup service'),
        ),
        migrations.AddField(
            model_name='installation',
            name='online',
            field=models.BooleanField(default=False, help_text='Online state'),
        ),
        migrations.AddField(
            model_name='installation',
            name='rb_service',
            field=models.BooleanField(default=False, help_text='RB service'),
        ),
        migrations.AddField(
            model_name='installation',
            name='tl_service',
            field=models.BooleanField(default=False, help_text='Time limit service'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='alarm',
            field=models.BooleanField(default=False, help_text='Alarm state'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='anti_drip',
            field=models.BooleanField(default=False, help_text='Anti-drip'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='inlet_pressure',
            field=models.IntegerField(blank=True, default=0, help_text='Inlet pressure (Bar)', null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='inlet_temperature',
            field=models.IntegerField(blank=True, default=0, help_text='Inlet temperature (°C)', null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='installation_code',
            field=models.CharField(default='default', help_text='CPx Code', max_length=255),
        ),
        migrations.AlterField(
            model_name='installation',
            name='outlet_pressure',
            field=models.IntegerField(blank=True, default=0, help_text='Outlet pressure (Bar)', null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='run',
            field=models.BooleanField(default=False, help_text='Running state'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='start_code',
            field=models.CharField(blank=True, default='0x0000', help_text='Start code', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='time_limit',
            field=models.BooleanField(default=False, help_text='Daily time limit reached'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='working_hours_counter',
            field=models.IntegerField(blank=True, default=0, help_text='Total working hours', null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='working_minutes_counter',
            field=models.IntegerField(blank=True, default=0, help_text='Working minutes', null=True),
        ),
    ]
