# Generated by Django 3.0.8 on 2020-07-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200729_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_imei', models.CharField(help_text='Recipient IMEI Code', max_length=255, unique=True)),
                ('command_string', models.CharField(help_text='Command string', max_length=255)),
            ],
        ),
    ]
