# Generated by Django 3.0.8 on 2020-07-29 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_commandlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommandList',
            new_name='Command',
        ),
    ]
