# Generated by Django 3.0.8 on 2020-07-29 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200729_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='recipient_imei',
        ),
        migrations.AddField(
            model_name='command',
            name='imei',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Installation'),
            preserve_default=False,
        ),
    ]
