# Generated by Django 3.0.8 on 2020-07-29 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200729_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='imei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Installation', unique=True),
        ),
    ]
