# Generated by Django 3.0.8 on 2020-07-29 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200729_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='command',
            name='imei',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Installation'),
        ),
    ]
