# Generated by Django 3.0.8 on 2020-07-29 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200729_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='id',
        ),
        migrations.AlterField(
            model_name='command',
            name='imei',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Installation'),
        ),
    ]
