# Generated by Django 3.0.8 on 2020-07-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200729_1038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Command',
        ),
    ]
