# Generated by Django 3.0.8 on 2020-07-29 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_string', models.CharField(help_text='Command string', max_length=255)),
                ('imei', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Installation')),
            ],
        ),
    ]
