# Generated by Django 3.0.8 on 2020-07-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='imei',
            field=models.CharField(help_text="Recipient's IMEI", max_length=255, unique=True),
        ),
    ]
